# Generated by Django 5.0.7 on 2024-07-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.IntegerField()),
                ('goal', models.TextField()),
                ('moral_type', models.CharField(max_length=20)),
                ('course_type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CourseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('goal', models.TextField()),
                ('creator', models.IntegerField()),
                ('relevant_for', models.CharField(max_length=20)),
                ('interactive', models.BooleanField()),
                ('multiple_choice_quiz', models.BooleanField()),
                ('info_screen', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
                ('furhter_resources', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoneCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('coures', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoneGoodThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('good_thing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoneQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('course_question', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('impact', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=20)),
                ('relevant_for', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LikedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=2)),
                ('age', models.IntegerField()),
                ('isAdmin', models.BooleanField()),
                ('categorical_imperative', models.IntegerField()),
                ('utilitarian', models.IntegerField()),
                ('virute_ethics', models.IntegerField()),
                ('animal_rights', models.IntegerField()),
                ('longtermism', models.IntegerField()),
                ('wants_to_become_vegetarian', models.BooleanField()),
                ('doing_good_streak', models.IntegerField()),
                ('not_eating_meat_streak', models.IntegerField()),
                ('course_streak', models.IntegerField()),
                ('joined_at', models.DateField()),
                ('total_time_on_the_app_in_minutes', models.BigIntegerField()),
                ('total_amount_of_donations', models.IntegerField()),
                ('donations_per_week_goal', models.IntegerField()),
                ('meat_days', models.CharField(max_length=12)),
                ('goodness_score', models.IntegerField()),
            ],
        ),
    ]
