# Generated by Django 5.0.7 on 2024-07-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequestion',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
