# Generated by Django 5.0.7 on 2024-08-07 21:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_coursequestion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doinggoodnetworkpost',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='likedposts',
            name='post',
        ),
        migrations.RemoveField(
            model_name='donegoodthings',
            name='good_thing',
        ),
        migrations.RemoveField(
            model_name='donegoodthings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Issues',
        ),
        migrations.RemoveField(
            model_name='likedposts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='animal_rights',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='categorical_imperative',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='doing_good_streak',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='donations_per_week_goal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goodness_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longtermism',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_amount_of_donations',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='utilitarian',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='virtue_ethics',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='meat_days',
            field=models.CharField(max_length=18),
        ),
        migrations.DeleteModel(
            name='DoingGoodNetworkPost',
        ),
        migrations.DeleteModel(
            name='GoodThing',
        ),
        migrations.DeleteModel(
            name='DoneGoodThings',
        ),
        migrations.DeleteModel(
            name='LikedPosts',
        ),
    ]
