# Generated by Django 5.0.7 on 2024-08-20 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_day_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='moral_type',
        ),
        migrations.RemoveField(
            model_name='coursequestion',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='coursequestion',
            name='furhter_resources',
        ),
        migrations.RemoveField(
            model_name='coursequestion',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='coursequestion',
            name='info_screen',
        ),
        migrations.RemoveField(
            model_name='coursequestion',
            name='interactive',
        ),
        migrations.RemoveField(
            model_name='coursequestion',
            name='multiple_choice_quiz',
        ),
        migrations.RemoveField(
            model_name='coursequestion',
            name='relevant_for',
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='next_question_if_false',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_if_false', to='backend.coursequestion'),
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='next_question_if_true',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_if_true', to='backend.coursequestion'),
        ),
    ]
