# Generated by Django 5.0.7 on 2024-08-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_course_course_type_remove_course_moral_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='creator',
        ),
    ]
