# Generated by Django 5.0.7 on 2024-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_course_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequestion',
            name='is_boolean',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='options',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
