# Generated by Django 5.0.7 on 2024-08-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_coursequestion_is_boolean_coursequestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
